dist: trusty
sudo: required

services:
  - docker
  
script:
  - docker pull nhdezoito/clang:latest
  - docker build --rm -f clang/Dockerfile -t slaves/clang:latest clang
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWD
  - docker push slaves/clang:latest
